name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    networks:
    - testing_net
    volumes:
    - type: bind
      source: ./server/config.ini
      target: /config/server_config.ini
  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_ID=1
    - NOMBRE=Pepito
    - APELLIDO=Gomez
    - DOCUMENTO=12345678
    - NACIMIENTO=1990-01-01
    - NUMERO=1234
    networks:
    - testing_net
    volumes:
    - type: bind
      source: ./client/config.yaml
      target: /config/client_config.yaml
    depends_on:
    - server
networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
